export const schoolRecords = [
  {
    schoolName: "中国科学技术大学",
    collegeName: "网络空间安全学院",
    province: "安徽省",
    startDate: "2026-04-18",
    endDate: "2026-05-08",
    rank: "华五",
    comLevel: "强com",
    hasExam: "是",
    link: "https://cybersec.ustc.edu.cn/",
  },
  {
    schoolName: "复旦大学",
    collegeName: "计算与智能创新学院",
    province: "上海市",
    startDate: "2026-05-12",
    endDate: "2026-05-28",
    rank: "华五",
    comLevel: "弱com",
    hasExam: "否",
    link: "https://www.fudan.edu.cn/",
  },
  {
    schoolName: "清华大学",
    collegeName: "计算机科学与技术系",
    province: "北京市",
    startDate: "2026-04-01",
    endDate: "2026-04-15",
    rank: "C9",
    comLevel: "强com",
    hasExam: "是",
    link: "https://www.tsinghua.edu.cn/",
  },
  {
    schoolName: "浙江大学",
    collegeName: "软件学院",
    province: "浙江省",
    startDate: "2026-04-24",
    endDate: "2026-05-20",
    rank: "C9",
    comLevel: "弱com",
    hasExam: "否",
    link: "https://www.zju.edu.cn/",
  },
  {
    schoolName: "武汉大学",
    collegeName: "信息管理学院",
    province: "湖北省",
    startDate: "2026-05-02",
    endDate: "2026-05-18",
    rank: "985",
    comLevel: "强com",
    hasExam: "是",
    link: "https://www.whu.edu.cn/",
  },
  {
    schoolName: "华南理工大学",
    collegeName: "电子与信息学院",
    province: "广东省",
    startDate: "2026-04-10",
    endDate: "2026-04-28",
    rank: "985",
    comLevel: "弱com",
    hasExam: "否",
    link: "https://www.scut.edu.cn/",
  },
  {
    schoolName: "北京邮电大学",
    collegeName: "网络空间安全学院",
    province: "北京市",
    startDate: "2026-05-08",
    endDate: "2026-06-01",
    rank: "211",
    comLevel: "强com",
    hasExam: "是",
    link: "https://www.bupt.edu.cn/",
  },
  {
    schoolName: "南京邮电大学",
    collegeName: "计算机学院",
    province: "江苏省",
    startDate: "2026-04-05",
    endDate: "2026-04-26",
    rank: "211",
    comLevel: "弱com",
    hasExam: "否",
    link: "https://www.njupt.edu.cn/",
  },
  {
    schoolName: "西南交通大学",
    collegeName: "信息科学与技术学院",
    province: "四川省",
    startDate: "2026-04-29",
    endDate: "2026-05-14",
    rank: "其他",
    comLevel: "强com",
    hasExam: "是",
    link: "https://www.swjtu.edu.cn/",
  },
  {
    schoolName: "哈尔滨工业大学",
    collegeName: "计算学部",
    province: "黑龙江省",
    startDate: "2026-05-18",
    endDate: "2026-06-05",
    rank: "C9",
    comLevel: "强com",
    hasExam: "是",
    link: "https://www.hit.edu.cn/",
  },
];

export const provinceOptions = [
  "全部",
  "北京市",
  "天津市",
  "河北省",
  "山西省",
  "内蒙古自治区",
  "辽宁省",
  "吉林省",
  "黑龙江省",
  "上海市",
  "江苏省",
  "浙江省",
  "安徽省",
  "福建省",
  "江西省",
  "山东省",
  "河南省",
  "湖北省",
  "湖南省",
  "广东省",
  "广西壮族自治区",
  "海南省",
  "重庆市",
  "四川省",
  "贵州省",
  "云南省",
  "西藏自治区",
  "陕西省",
  "甘肃省",
  "青海省",
  "宁夏回族自治区",
  "新疆维吾尔自治区",
  "香港特别行政区",
  "澳门特别行政区",
  "台湾省",
];
